package com.apm.payments.models;

import com.apm.payments.enums.ProviderType;
import com.apm.payments.enums.PaymentMethodType;

import java.io.Serializable;

/**
 * Created by Ing. Oscar G. Medina Cruz on 26/06/18.
 */
public class PaymentData implements Serializable {

    private String payment_source_id;
    private int payment_method_id;
    private String method;
    private String currency;
    private String device_session_id;
    private final String origin = "Android";
    private String provider;

    //region GETTERS
    public String getPaymentSourceId() {
        return payment_source_id;
    }

    public int getPaymentMethodId() {
        return payment_method_id;
    }

    public String getMethod() {
        return method;
    }

    public String getCurrency() {
        return currency;
    }

    public String getDeviceSessionId() {
        return device_session_id;
    }

    public String getProvider() {
        return provider;
    }
    //endregion

    //region SETTERS

    /**
     * Establishes the payment source id
     * @param paymentSourceId   The payment source id to do the payment
     */
    public void paymentSourceId(String paymentSourceId) {
        this.payment_source_id = paymentSourceId;
    }

    /**
     * Establishes the payment method id
     * @param paymentMethodId   The provider method id to do the payment
     */
    public void paymentMethodId(int paymentMethodId) {
        this.payment_method_id = paymentMethodId;
    }

    /**
     * Establishes the payment method type
     * @param method    The {@link PaymentMethodType} to do the payment
     */
    public void method(PaymentMethodType method) {
        method(method.toString().toLowerCase());
    }

    /**
     * Establishes the payment method type
     * @param method    The {@link PaymentMethodType} to do the payment as String
     */
    public void method(String method) {
        this.method = method.toLowerCase();
    }

    /**
     * Establishes the currency
     * @param currency  The payment currency to do the payment
     */
    public void currency(String currency) {
        this.currency = currency;
    }

    /**
     * Establishes the device session id generated by OneSignal
     * @param deviceSessionId   Device session id generated by OneSignal SDK
     */
    public void deviceSessionId(String deviceSessionId) {
        this.device_session_id = deviceSessionId;
    }

    /**
     * Establishes the provider type from provider list
     * @param provider  The {@link ProviderType} to do the payment
     */
    public void provider(ProviderType provider) {
        this.provider = provider.toString().toLowerCase();
    }

    /**
     * Establishes the provider type from provider list
     * @param provider  The {@link ProviderType} to do the payment as String
     */
    public void provider(String provider) {
        this.provider = provider.toLowerCase();
    }
    //endregion
}
